package pt.isel.ls.domain

import kotlin.test.Test
import kotlin.test.assertFailsWith

class EmailTest {
    @Test
    fun `good email creation test`() {
        Email("good@emailTest.com")
    }

    @Test
    fun `exception generated by a bad instantiation of an Email test`() {
        assertFailsWith<IllegalArgumentException> { Email("badEmail") }
    }
}
